#!/usr/bin/env node --harmony

const program = require('commander');
const { updateCommand } = require('./lib/update.js');

program
  .version('0.0.1')
  .description('Node command line tool for managing package.json version')

program
  .command('update <to>')
  .description('update version of package.json')
  .option('-b, --branch [branch]', 'source branch for evaluating next version', 'master')
  .option('-t, --access_token [token]', 'access token used for github')
  .option('-o, --owner [owner]', 'owner of github repo')
  .option('-r, --repo [repo]', 'github repo')
  .option('-n, --number [pr number]', 'number of pull request')
  .action(updateCommand);

program.parse(process.argv);
